version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-books
      - IMAGE_TAG=latestbuild
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - mvn clean package
  build:
    commands:
      - echo Build started on `date`
      - echo building the Docker image
      - docker build -t vertx/books .
      - docker tag 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-books:latest 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-books:latestbuild
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing the Docker image
      - docker push 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-books:latest
      - docker push 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-books:latestbuild
artifacts:
  files:
    - target/books-1.0.0-SNAPSHOT-fat.jar
